apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    compileSdk 35

    defaultConfig {
        applicationId "in.nitinja.portforwarder"
        minSdkVersion 23
        targetSdkVersion 35
        versionCode 1
        versionName "0.0.1"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
    namespace 'com.elixsr.portforwarder'
}
kotlin {
    jvmToolchain(21)
}
dependencies {
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.percentlayout:percentlayout:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'com.github.paolorotolo:appintro:4.0.0'
    testImplementation 'junit:junit:4.13.2'
}
